# Development stage
FROM node:18 AS development
  
# Create app directory
WORKDIR /usr/src/app
  
# Copy application dependency manifests to the container image.
COPY package*.json ./
  
# Install app dependencies using the `npm ci` command instead of `npm install`
RUN npm ci
  
# Install Prisma CLI globally
RUN npm install -g prisma
  
# Copy Prisma schema file
COPY prisma ./prisma/
  
# Generate Prisma client
RUN prisma generate
  
# Bundle app source
COPY . .
  
# Use the node user from the image (instead of the root user)
USER node
  
# Run in dev Mode: npm run start:dev
CMD ["npm", "run", "start:dev"]
